version: '3'

services:
  app-frontend:
    image: next-app-frontend
    build:
      context: './frontend'
    ports:
      - 3000:3000
    networks:
      - salary-api-network
    depends_on:
      - app-backend

  app-backend:
    image: go-app-backend
    build:
      context: './backend'
    ports:
      - 8000:8080
    networks:
      - salary-api-network
    links:
      - db
    depends_on:
      - db
  db_admin:
    image: mongo-express
    ports:
      - 3001:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    links:
      - db
    depends_on:
      - db
    networks:
      - salary-api-network

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "3002:27017"
    volumes:
      - .docker-volumes/mongo-data:/data/db
    networks:
      - salary-api-network

networks:
  salary-api-network:
    driver: bridge